# Generated by Django 5.1.2 on 2025-05-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default-3.jpg', null=True, upload_to='avatars', verbose_name='фото профиля'),
        ),
    ]
