# Generated by Django 5.1.4 on 2025-02-28 06:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Роль')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('release_date', models.DateField(verbose_name='Дата выхода')),
                ('premium', models.BooleanField(default=False)),
                ('price', models.PositiveBigIntegerField(null=True)),
                ('poster', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='movies/posters/')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Описание')),
                ('movie_length', models.PositiveBigIntegerField(verbose_name='Длительность в минутах')),
                ('bg_photo', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='movies/bg_photos')),
                ('trailer_url', models.URLField(verbose_name='Ссылка на трейлер')),
                ('video_360', models.FileField(blank=True, null=True, upload_to='movies/videos/360/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('video_720', models.FileField(blank=True, null=True, upload_to='movies/videos/720/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('video_1920', models.FileField(blank=True, null=True, upload_to='movies/videos/1920/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('video_4k', models.FileField(blank=True, null=True, upload_to='movies/videos/4k/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('created_at', models.DateField(auto_now_add=True)),
                ('all_views', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='movies', to='movie.country')),
                ('genres', models.ManyToManyField(to='movie.genre', verbose_name='Жанры')),
            ],
        ),
        migrations.CreateModel(
            name='MovieFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='movie/frames/')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='movie.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Имя')),
                ('photo', models.ImageField(upload_to='persons/', verbose_name='Фотографии')),
                ('movies', models.ManyToManyField(blank=True, to='movie.movie', verbose_name='Фильмы')),
            ],
        ),
        migrations.CreateModel(
            name='PersonRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='roles', to='movie.person', verbose_name='Человек')),
                ('roles', models.ManyToManyField(to='movie.role', verbose_name='Роли')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='persons',
            field=models.ManyToManyField(to='movie.personrole', verbose_name='Люди'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='MovieViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='views', to='movie.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'movie')},
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='movie.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'movie')},
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Оценка')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ratings', to='movie.movie', verbose_name='Фильм')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
