# Generated by Django 5.1.4 on 2025-02-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_country_remove_movie_rating_movie_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='movies',
            field=models.ManyToManyField(null=True, to='movie.movie', verbose_name='Фильмы'),
        ),
    ]
