# Generated by Django 5.1.2 on 2025-05-31 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videostream',
            old_name='hls',
            new_name='hls_parh',
        ),
        migrations.AddField(
            model_name='videostream',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2025, 6, 1, 2, 17, 7, 772227), verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videostream',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='videostream',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
