# Generated by Django 4.2.5 on 2024-06-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0003_alter_movies_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
