# Generated by Django 5.1.2 on 2025-06-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_rename_hls_videostream_hls_parh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videostream',
            name='resolution',
            field=models.PositiveIntegerField(),
        ),
    ]
