# Generated by Django 5.1.2 on 2025-06-01 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_videostream_resolution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videostream',
            old_name='hls_parh',
            new_name='hls_path',
        ),
    ]
