# Generated by Django 5.1.2 on 2025-06-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_rename_hls_parh_videostream_hls_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videostream',
            name='resolution',
            field=models.CharField(choices=[('360', '360'), ('480', '480'), ('720', '720'), ('1080', '1080')], max_length=10),
        ),
    ]
