# Generated by Django 5.1.2 on 2025-06-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_videostream_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='master_hls_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Путь к master.m3u8'),
        ),
    ]
