# Generated by Django 5.1.2 on 2025-06-01 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_movie_master_hls_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='master_hls_path',
            new_name='hls_master',
        ),
    ]
