# Generated by Django 5.1.2 on 2025-06-04 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_alter_personsubscription_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='updated_at',
        ),
    ]
