# Generated by Django 5.1.2 on 2025-06-04 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_remove_watchlist_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2025, 6, 4, 12, 50, 0, 630357), verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
