# Generated by Django 5.1.2 on 2025-06-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_movie_recommendations_alter_movie_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='bg_photo',
            field=models.ImageField(blank=True, default='defaults/default-bg.jpg', null=True, upload_to='movies/bg_photos/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, default='defaults/poster.jpg', null=True, upload_to='movies/posters/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(default='defaults/person.jpg', upload_to='persons/<django.db.models.fields.CharField>/', verbose_name='Фотографии'),
        ),
    ]
